### ISSUE TITLE
"We plan to release the software as open-source in early June 2015"

### ISSUE THREAD

**Issue by guizmaii** [gilt/ionroller#1]
It's "early June 2015" ! =)

Do you have a more precise idea now of when you will open it ?

We're greatly interessed !

**Comment by dan-v** [comment]
+1

**Comment by imsky** [comment]
:+1:

**Comment by JakubKahovec** [comment]
+1

**Comment by damnhandy** [comment]
:+1:

**Comment by lad** [comment]
Patiently waiting. The writeup at InfoQ was great, would love to see some code

**Comment by fiadliel** [comment]
Sorry, just waiting for a quick security checkup on the code, so it should be soon.

**Comment by zhangcheng-aa** [comment]
+1

**Comment by zhangcheng** [comment]
+1

**Comment by janjilek** [comment]
+1

**Comment by kian** [comment]
+1 - really interested in seeing this code after watching [Michael's talk](https://www.youtube.com/watch?v=GaHzdqFithc)

**Comment by vjc** [comment]
@fiadliel any more updates?

**Comment by nataliab** [comment]
ION-Roller code in now available! Make sure to check out the demo as well: https://drive.google.com/file/d/0B4LFRaB4aCbcRFRra0JOcUJnRVk/view?usp=sharing

**Comment by guizmaii** [comment]
Great ! Thanks =)

**Comment by JakubKahovec** [comment]
Thank you !

**Comment by razvanz** [comment]
Great stuff :+1:

**Comment by imsky** [comment]
![](http://gifs.joelglovier.com/excited/cookie-monster.gif)
